// Generated by Payload (`payload generate:importmap`). Maps custom admin
// components into the bundle. Empty until custom components are registered;
// regenerated automatically as the CMS grows.
export const importMap = {};
